### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by facundoy** [AgentTorch/AgentTorch#25]
When installing AgentTorch we got some errors regarding the torch and jaxlib module versions. We solved this by reinstalling in a python 3.8 environment. I believe this was mentioned in the previous tutorial, but not in the current one.

**Comment by gamemaker1** [comment]
Hi @facundoy,

Thanks for opening this issue.

> When installing AgentTorch we got some errors regarding the torch and jaxlib module versions.

What errors did you see? What version of Python and AgentTorch were you using before you reinstalled everything in Python 3.8?

> I believe this was mentioned in the previous tutorial, but not in the current one.

AgentTorch is to be used in a Python 3.9 environment. I will add that to the readme and installation docs right away, thank you for pointing out that it was missing.

**Comment by facundoy** [comment]
When I tried installing the framework using `> pip install git+https://github.com/agenttorch/agenttorch`, I got the following error: 
```
ERROR: Could not find a version that satisfies the requirement torch==2.1.2 (from agent-torch) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1)
ERROR: No matching distribution found for torch==2.1.2
```

I also tried running `pip install agent_torch`, and I got the following error: 
```
ERROR: Cannot install agent-torch==0.2.2, agent-torch==0.2.3 and agent-torch==0.2.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    agent-torch 0.2.4 depends on jaxlib==0.4.13
    agent-torch 0.2.3 depends on jaxlib==0.4.13
    agent-torch 0.2.2 depends on jaxlib==0.4.13

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by gamemaker1** [comment]
> ERROR: Could not find a version that satisfies the requirement torch==2.1.2 (from agent-torch) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1)
> ERROR: No matching distribution found for torch==2.1.2

I think [this](https://stackoverflow.com/a/77399075) might be causing that error to pop up.

We might try upgrading the version of `pytorch` we use so that you can use the library with a more recent version of python.

> I also tried running pip install agent_torch, and I got the following error: ...

The pip package is currently out of date; we are currently working on setting up a release process to make sure it is updated.

**Comment by ayushchopra96** [comment]
Closing this issue. Please let us know if you have any other installation issues.
