### ISSUE TITLE
Would Like to Contribute

### ISSUE THREAD

**Issue by gamemaker1** [AgentTorch/AgentTorch#8]
Hi @ayushchopra96,

I came across this repository and found the concept of using agents to simulate and solve for large-scale problems interesting. I glanced through the code and loved the architecture of the project: reducing the complexity of a population-scale problem into three simple steps of configuring a model, creating substeps, and then executing it with a runner.

I have been [contributing to and maintaining](https://gamemaker1.github.io) popular open source projects such as Express Rate Limit and have created a knowledge retrieval and extraction project called Dabbu. I've also contributed to population scale projects such as Sunbird and Beckn.

I would like to contribute to this project - to add new models, help fix bugs or deploy it in different scenarios. Please do let me know how I can get started.

Thank you,
Vedant

**Comment by ayushchopra96** [comment]
Hi @gamemaker1 thanks for your interest! Glad you like the project. Love your background.
There are a lot of open problems you can contribute to.

I'm still setting up a contributor onboarding doc. 
Can you email me at ayushc@mit.edu and we can setup a quick call to get you started!

**Comment by gamemaker1** [comment]
Great! I'll email you right away.
